heat_template_version: 2015-10-15
description: Launch a basic instance with CirrOS image using the
             ``m1.tiny`` flavor, ``mykey`` key,  and one network.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: cirros
      file: license=/home/stack/FG-licenses/FGVM080000103268.lic
      flavor: m1.tiny
      key_name: mykey
      networks:
      - network: { get_param: NetID }
      - netowrk: external_network

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server, first_address ] }
    description: Launch a basic instance with CirrOS image using the ``m1.tiny`` flavor,
  ``mykey`` key,  and one network.